services:
  web:
    build:
      context: .
      target: development
      args:
        - BUILD_CONFIGURATION
        - HOST_USER_ID
    volumes:
      - ./:/src/
    links:
      - db:db
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80'